# Site
repository: IrePin/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ilya Repin
title: Unity 3d Developer, Sound Designer
email: gagistos@gmail.com
website: https://irepin.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: IlaRepin1
github_username:  IrePin
instagram_username: enemixx
linkedin_username: ilrepin
youtube_username: "@gagistos3926"


# Additional icon links
additional_links:
- title: IrePin
  icon: fas fa-globe
  url: https://irepin.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ilya and I'm Unity 3d developer. Throughout last year, I made significant progress in enhancing my skills as a Unity developer. 
  My daily efforts focused on teamwork, effective communication, thorough research, and continuous learning of programming languages, with a particular emphasis on object-oriented programming.
  As a result of my project-based learning and self-teaching experiences, I possess knowledge of the Unity Engine and C#. 
  I am currently seeking a career as a Game Developer, and I believe my passion for continuous learning and self-improvement
  will be invaluable in achieving my goals. With a proactive mindset, I am committed to daily growth and development,
  and eager to leverage my talents and expertise to make meaningful contributions in the field.

  I am most skilled in:<mark>Unity</mark>, <mark>FMOD</mark> and <mark>Sound Design</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Scavenging Roots
        link: https://hazkin.itch.io/scavenging-roots
        # link_text: Project Website
        additional_links:
          - title:  Scavenging Roots Github
            icon: fab fa-github
            url: github.com/IliaValianov/GBP
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          We developed this game for Global Game Jam 2023
        description: | # this will include new lines to allow paragraphs
         We developed this game in a week, with a team of 7 people. my role in the project is <mark>Sound Design</mark>. I completely wrote the soundtrack and programmed the <mark>FMOD</mark>.
         I gained a lot of skills through this project and I am very proud to have it in my portfolio.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IrePin Games
        link: github.com/IrePin-Games/Cats_TBS
        # link_text: boringcompany.com
        sub_title: Unity 3d Developer
        caption: august 2022 - Present
        quote: >
          Developing a step-by-step strategy game called CATS vs Zorbo
        description: | # this will include new lines to allow paragraphs
            IrePin-Games is my project where I develop a couple of games in the same universe. The games are about a confrontation between the C.A.T.S. special unit and the "Zorbo" organization,
            which wants to take over the world and impose its authoritarian, slave-like worldview on the whole world. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Udemy
        caption: 2022 - 2022
        sub_title: Unity Turn-Based Strategy Game Intermediate C# Coding
        link: http://surl.li/ezymx

        quote: >
          Udemy is an online learning platform that offers courses on a wide range of subjects, including business, technology, design, and personal development.
        description: | # this will include new lines to allow paragraphs
          Throughout this course, I was able to elevate my skills from a beginner level to an advanced level. I gained valuable knowledge on managing and organizing complex projects, created a custom Grid System, and learned advanced programming concepts including C# generics, C# events, and custom structs. In addition, I also learned about A* Pathfinding, which was an added bonus.

      - layout: left
        title: Udemy
        caption: 2022 - 2022
        sub_title: Unity Turn-Based Strategy Game Intermediate C# Coding
        link: http://surl.li/ezymx 
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
